version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker: 
      - image: circleci/python:3.8
      - image: circleci/mysql:5.7.28
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password

    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          commnad: |
            echo 'export DB_NAME="test_db"' >> $BASH_ENV
            echo 'export DB_USER="user"' >> $BASH_ENV
            echo 'export PASSWORD="password"' >> $BASH_ENV
            echo 'export DB_HOST="localhost"' >> $BASH_ENV
            echo 'export DB_PORT=3306' >> $BASH_ENV
            source $BASH_ENV
          name: Add database Connection Environment Variables
      - run:
          command: pip install -r requirements.txt
          name: Install Dependencies
      - run:
          command: python manage.py test .
          name: Test
          
workflows:
  main:
    jobs:
      - build-and-test