version: 2.1
orbs:
  python: circleci/python@0.2.1
jobs:
  build-and-test:
    docker: 
      - image: circleci/python:3.8
      - image: circleci/mysql:5.7.28
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: |
            echo 'export DB_NAME="test_db"'      >> $BASH_ENV
            echo 'export DB_USER="user"'         >> $BASH_ENV
            echo 'export DB_PASSWORD="password"' >> $BASH_ENV
            echo 'export DB_HOST="localhost"'    >> $BASH_ENV
            echo 'export DB_PORT=3306'           >> $BASH_ENV
            echo 'export SECRET_KEY="secret"'    >> $BASH_ENV
            source $BASH_ENV
          name: Add Database Connection Environment Valiables
      - run:
          command: pip install -r requirements.txt
          name: Install Dependencies
      - run:
          name: Waiting For MySQL To Be Ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          command: python manage.py makemigrations
      - run:
          command: python manage.py migrate
      - run:
          command: python manage.py test .
          name: Test
workflows:
  main:
    jobs:
      - build-and-test